name: sonar cloud scan
uses: /.github/workflows/main.yml
  with: |
    go-version: 5.3.0
    go-version-file: go.work file.
    check-latest: true
    token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
    cache: true
    cache-dependency-path: - go.sum
    architecture: x64
          
