name: sonar_cloud_scan_GitHub_action
on:
  workflow_dispatch:

jobs:
  sonarcloudscan:
    runs on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.3.0
with:
    fetch depht:
    go-version: 5.3.0
    go-version-file: go.work file.
    check-latest: true
    token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
    cache: true
    cache-dependency-path: go.work file.
    architecture: x64
          
